version: '3.8'

services:

  kanban_db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  kanban-backend:
    build: ./kanban-service
    ports:
      - "3003:3003"
    environment:

      - DATABASE_URL=${DATABASE_URL_DOCKER}
      - FRONTEND_URL=http://localhost:5173
      - PORT=3003
    depends_on:
      - kanban_db
    restart: on-failure


  kanban-frontend:
    build: ./kanban-web
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3003
    depends_on:
      - kanban-backend

    volumes:
      - ./kanban-web:/app
      - /app/node_modules

volumes:
  postgres_data:
